### ISSUE TITLE
.env file being pushed to repo?

### ISSUE THREAD

**Issue by Beacon24** [Beacon24/v0#13]
I have `.env` listen in my `.gitignore` file, but when I pushed my local updates to the github repo just now, it uploaded the`.env` file as well. I manually deleted the `.env` file but want to make sure this does not keep happening.

**Comment by selaguardia** [comment]
try removing the first 3 lines of index.js and require dotenv under all your imports.

**Comment by Beacon24** [comment]
I think I need those top 3 lines for running the code in production mode through heroku, is this possible?

Either way, next time I have a chance I will try what you say. Thanks for the tip!

**Comment by selaguardia** [comment]
I have my node express project deployed on heroku, and I just have `require('dotenv').config();` on its own line after I require express. It might not do anything, I'm still a new software engineer, but I don't see why your .env file would be uploaded. You included it in your .gitignore file. you have dotenv installed in your pachage.json that usually would do it for me. 

If that doesn't work, try this...
https://gist.github.com/gjerokrsteski/e4a10352448158ba827493eb116cda51

**Comment by lukebelliveau** [comment]
possible fix: https://github.com/Beacon24/v0/pull/17

**Comment by Beacon24** [comment]
Ok, I tried your fix, but now I am wondering, when someone else wants to pull and use the app, where do they get the tokens from? Do I need to explain how to generate each token in the readme, or point to the docs that do so?

**Comment by Beacon24** [comment]
So, now I am trying to test the gitignore by pushing from my computer to the repo, but am getting this message:
```
$ git push -u origin main
To https://github.com/Beacon24/v0.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'https://github.com/Beacon24/v0.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

This has happened before. I vaguely understand whats going on, sometimes. 

I tried running `$ git pull` and get:

```
From https://github.com/Beacon24/v0
   92ff8c9..ab2c7ec  main       -> origin/main
 * [new branch]      remove-env -> origin/remove-env
CONFLICT (modify/delete): .env deleted in ab2c7ecc688db414c1584c0672300f5bd6b3bc37 and modified in HEAD. Version HEAD of .env left in tree.
Automatic merge failed; fix conflicts and then commit the result.
```

I keep running into this issue, I think when I make changes on github and not my machine, but I'm not completely sure.

**Comment by lukebelliveau** [comment]
the issue here is basically that you have changes locally that are not in the remote repo (on github), and vice-versa. _in the future_, i think doing a "git pull rebase" should fix it (i normally rebase when I pull, it shifts the commits around so they're arranged in order rather than trying to merge commits together).

`git pull -r`
`git push`

in this case, you already have a conflict. you have two options.
**this first option is destructive and will cause you to lose any changes that are stored on your local machine that have not been pushed to Github. use with caution, and do not use unless you are positive there is not work on your machine that is not yet on Github.** (the `git stash` command will temporarily save your work, but still, better safe than sorry)
https://stackoverflow.com/a/72751476/3124493

if you're not sure about this, just delete the `.env` file and make a new commit:

`rm .env`
`git add .`
`git commit -m "remove .env file again"`
`git push`

**Comment by Beacon24** [comment]
Ok, but without the .env file on my local machine, won't I be unable to run the app locally?

**Comment by Beacon24** [comment]
alright, yes, that fixed it, I deleted .env, pushed, restored .env on my local machine, tried pushing again, and this time the `.gitignore` worked! thanks!
